### ISSUE TITLE
Hacer que la vida de los mobs solo se vea al ser atacados

### ISSUE THREAD

**Issue by chistian95** [ElZoo/Zooloween#12]
Ahora que ya están los ataques hechos, se puede hacer esto.
Como está ahora, la barra de vida de los mobs solo es visible cuando se acercan a ti.

Hacer que solo sean visibles durante unos segundos cuando el jugador principal les pega (supongo que se podría hacer con un tween de esos).

**Comment by Acunnia** [comment]
Resuelto en commit <commit>105832d614281650e534ac95f2844bbbdba2f9a9</commit>
