### ISSUE TITLE
Añadir golpes críticos

### ISSUE THREAD

**Issue by chistian95** [ElZoo/Zooloween#18]
Hacer que haya una pequeña probabilidad de realizar un golpe crítico.

- [x] Crear nuevo atributo de jugador en server.js llamado probCrit.
- [x] En server.js en la función player_atacar calcular la probabilidad según el atributo probCrit y duplicar el daño realizado.
- [x] Añadir el atributo probCrit a las armas en server.js (item_mano, item_daga, etc) con valores distintos.
- [x] En la función ponerArma de server.js actualizar el atributo probCrit del jugador.

**Comment by Acunnia** [comment]
Resuelto en el commit <commit>6e81cb64c42fd5a712afcf8baf15c062953c2384</commit>
