### ISSUE TITLE
Ampliar el mapa

### ISSUE THREAD

**Issue by chistian95** [ElZoo/Zooloween#2]
Ampliar las plataformas actuales o añadir nuevas. Crear nuevos items en dungeon.json y añadirlos al mapa.

- [x] Crear una plataforma en la parte de abajo del mundo.
- [x] Añadir la puerta cerrada a dungeon.json
- [x] Añadir las espadas y lanzas decorativas a dungeon.json
- [x] Poner los items decorativos en el mundo.

**Comment by Acunnia** [comment]
Resuelto en el commit <commit>349d37ac95805779360e7f4b7f5afbdf87d04fa7</commit>
