### ISSUE TITLE
Nivel medio de la arena

### ISSUE THREAD

**Issue by chistian95** [ElZoo/Zooloween#30]
Hacer que el servidor calcule cual es el nivel medio de la arena.
Para ello hay que sumar los niveles de todos los jugadores y dividirlo por la cantidad de jugadores que haya.

No hace falta que la llame en ningún lado porque esto no va a servir para nada ahora mismo, pero nos será útil más adelante.

**Comment by Acunnia** [comment]
Resuelto en commit <commit>6226fe1687a8e40ad1028d383d95f682c48b5313</commit>
