### ISSUE TITLE
Panel de info sobre los botones

### ISSUE THREAD

**Issue by chistian95** [ElZoo/Zooloween#37]
Hacer que al poner el ratón sobre los dos botones del hud (los de arma y armadura), salga un pequeño panel con información.

Creo que habría que ponerle .setInteractive() al final de la función de crear el sprite ->
this.add.sprite(...).setScale(...).setInteractive()

 Con eso registra eventos, luego poner -> 
miSprite.on('mousein', function() { //mostrar pantalla }, this);

miSprite.on('mouseout', function() { //ocultar pantalla }, this);

Supongo que se podría preparar un container con un sprite para hacer de fondo y el texto con la descripción y ponerlo invisible nada mas crearlo y luego en los eventos esos hacerlos visibles.

Ahora mismo el cliente no tiene ni idea de los stats de las armas. Tal vez se le podrían pasar al crear la conexión en el método que hay en server.js que se llama "socket.emit('datosMapa..." y recogerlo en precarga.js en "this.game.datos.socket.on('datosMapa', ..."

Habría que esperar también a terminar la tarea #34 para poner la info de la armadura

**Comment by mancanjua** [comment]
Terminado en: 41d08dd596a6d20c110d1ecbf5bf3540a4dcfc19
