### ISSUE TITLE
Cuando el pj esté quieto que mire en la última dir que se movió

### ISSUE THREAD

**Issue by chistian95** [ElZoo/Zooloween#5]
Ahora mismo cuando un player deja de moverse se le asigna una dirección 'quieto' que hace que mire hacia abajo.

Hacer que se le asigne 'quieto_arriba', 'quieto_abajo', 'quieto_izquierda' o 'quieto_derecha' dependiendo de la dirección en la que se estaban moviendo previamente.

Editar también la animación de atacar del player y hacer que ataque en la dirección que esté mirando (hay que crear las nuevas anims, se puede basar en la que hay ahora de ataque).

- [x] Preservar dirección en el movimiento
- [x] Preservar dirección en el ataque

**Comment by chistian95** [comment]
Primer punto resuelto en: fdee52a169c31d6a1809987245ee5005583a0d17

**Comment by mancanjua** [comment]
Terminado en commit: <commit>fd391247e509d9868687b6def36e8c8eb131f206</commit>
