### ISSUE TITLE
Balancear items

### ISSUE THREAD

**Issue by chistian95** [ElZoo/Zooloween#64]
Cambiar los siguientes stats:

Armas:
	- Mano: Igual que ahora
	- Daga: Igual que ahora
	- Lanza:
		delay: 35
	- Hacha:
		lvl: 30
	- Martillo:
		daño: 35
		lvl: 45

Armaduras:
	- Tela: Igual que ahora
	- Cuero: 
		vida: 70
	- Cadenas:
		vida: 90
	- Hierro:
		lvl: 40
		vida: 120
	- Oro:
		lvl: 60
		vida: 150

**Comment by Acunnia** [comment]
Resuelto en <commit>5ce5d2288f8d420bb7d7344c11c223acd4be2c47</commit>
